import os
import stat
from operator import add
from functools import reduce
from itertools import product
from SCons.Action import ActionFactory

BENCHMARKS = {
    'int': [
        # Int
        "400.perlbench",
        "401.bzip2",
        "403.gcc",
        "429.mcf",
        "445.gobmk",
        "456.hmmer",
        "458.sjeng",
        "462.libquantum",
        "464.h264ref",
        "471.omnetpp",
        "473.astar",
        "483.xalancbmk",
    ],
    'fp': [
        # FP
        "410.bwaves",
        #"416.gamess", #FIXME: underflow flag
        "433.milc",
        "434.zeusmp",
        "435.gromacs",
        "436.cactusADM",
        "437.leslie3d",
        "444.namd",
        #"447.dealII", #FIXME: compile error
        #"450.soplex", #FIXME: compile error
        "453.povray",
        "454.calculix",
        "459.GemsFDTD",
        "465.tonto",
        "470.lbm",
        #"481.wrf", #FIXME: underflow flag
        "482.sphinx3",
    ]
}

def _write_commands(target, binary, command):
    with open(target, 'w') as _f, open(command, 'r') as _c:
        _f.write('#!/bin/sh\n')
        _f.write('cd /root\n')
        for line in _c:
            _f.write('echo "run ./%s %s"\n' % (binary, line))
            _f.write('./%s %s\n' % (binary, line))
        _f.write('poweroff\n')
    os.chmod(target, os.stat(target).st_mode | stat.S_IEXEC)

WriteCommands = ActionFactory(
    _write_commands,
    lambda target, binary, command:
    'WriteCommands("%s", "%s", "%s")' % (target, binary, command))

def _spec_actions(source, target, env, for_signature):
    config = os.path.splitext(source[-1].name)[0]
    prefix = os.path.join(env['SPEC2006_DIR'], 'benchspec', 'CPU2006')
    run_dirs = [
        os.path.join(
            prefix, benchmark, 'run',
            'run_base_%s_%s.0000' % (env['INPUT'], config))
        for benchmark in BENCHMARKS[env['SUITE']]
    ]
    WriteInit = env['WRITE_INIT']
    return [
        # Compile SPEC
        Copy(os.path.join(env['SPEC2006_DIR'], source[-1].name), source[-1]),
        ' '.join([
            'cd', env['SPEC2006_DIR'], '&&',
            'source', './shrc', '&&', 'runspec',
            '--action', 'setup',
            '--config', config,
            '--size', env['INPUT'],
            '--parallel_setup', str(GetOption('num_jobs'))
        ] + BENCHMARKS[env['SUITE']])
    ] + reduce(add, [
        [
            # Install overlays
            Delete(binary.dir.abspath),
            Copy(binary.dir.abspath, run_dir),
            Delete(os.path.join(binary.dir.abspath, '..', 'etc', 'init.d')),
            Mkdir(os.path.join(binary.dir.abspath, '..', 'etc', 'init.d')),
            WriteCommands(
                os.path.join(binary.dir.abspath, '..', 'etc', 'init.d', 'rcS'),
                binary.name,
                command.abspath),
            WriteInit(
                os.path.join(binary.dir.abspath, '..', 'etc', 'init.d', 'rcK'),
                '\n'.join(['#!/bin/sh', '# Do nothing']))
        ]
        for run_dir, binary, command in zip(run_dirs, target, source[:-1])
    ], [])

def main():
    Import('env')

    env.Append(BUILDERS={
        'SPEC2006': Builder(generator=_spec_actions)
    })

    spec2006 = dict()
    for suite, input_type in product(['int', 'fp'], ['test', 'ref']):
        commands = [
            os.path.abspath(os.path.join(
                'commands', '%s.%s.cmd' % (benchmark, input_type)))
            for benchmark in BENCHMARKS[suite]
        ]
        binaries = [
            os.path.join(
                env['OVERLAY_DIR'], benchmark + '.' + input_type, 'root',
                'sphinx_livepretend_base.riscv'
                if benchmark == '482.sphinx3'
                else 'Xalan_base.riscv'
                if benchmark == '483.xalancbmk'
                else benchmark[4:] + '_base.riscv')
            for benchmark in BENCHMARKS[suite]
        ]
        build = env.SPEC2006(
            binaries,
            commands + ['riscv.cfg'],
            SUITE=suite,
            INPUT=input_type)
        env.SideEffect('#spec2006', build)
        spec2006[suite, input_type] = zip(BENCHMARKS[suite], build)

    return spec2006

if __name__ == 'SCons.Script':
    spec2006 = main()
    Return('spec2006')
