#!/bin/sh
#

SYSLOGD_ARGS=-n
KLOGD_ARGS=-n

hello() {
  echo "Hello Linux!"
  poweroff
}

case "$1" in
  start)
	hello
	;;
  stop)
	# do nothing
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

