import os
from operator import add
from functools import reduce

def build_custom_bmark(env, bmark):
    build = os.path.abspath(os.path.join(bmark, 'build'))
    env.VariantDir(build, bmark, duplicate=0)
    binary = env.Program(
        os.path.join(build, bmark),
        Glob(os.path.join(bmark, '*.c')) + \
        Glob(os.path.join(bmark, '*.S')))
    env.Alias(bmark, binary)
    overlay_dir = os.path.join(env['OVERLAY_DIR'], bmark)
    overlay_files = env.Overlay(
        os.path.join(overlay_dir, 'root', binary[0].name),
        binary,
        OVERLAY=overlay_dir,
        rcS="""
#!/bin/sh
echo "Run: /root/{bmark}/"
/root/{bmark}
poweroff""".format(bmark=bmark))
    return env['BUILD_BBLVMLINUX'](env, bmark, overlay_dir, overlay_files)

def main():
    Import('env')

    riscv_bin = os.path.join(env['ENV']['RISCV'], 'bin')
    riscv_gcc_opts = ' '.join([
        '-I' + os.path.abspath('common'),
        '-O2',
        '-DPREALLOCATE=1',
        '-mcmodel=medany',
        '-march=rv64imafd',
        '-Wa,-march=rv64imafdxhwacha'
    ])
    _env = env.Clone(
        CC=os.path.join(riscv_bin, 'riscv64-unknown-elf-gcc'),
        CCFLAGS=riscv_gcc_opts,
        ASPPFLAGS=riscv_gcc_opts,
    )

    custom_bmarks = [
        f for f in os.listdir(os.path.curdir)
        if os.path.isdir(f) and f != 'common'
    ]
    for bmark in custom_bmarks:
        bblvmlinux = build_custom_bmark(_env, bmark)
        env.Alias('build-' + bmark, bblvmlinux)
        env.Alias('run-' + bmark, env.Spike('#run-' + bmark, bblvmlinux))

if __name__ == 'SCons.Script':
    main()
